const PAD_ORDER = [
  {"name": "PAD 01", "position": "top left shoulder"},
  {"name": "PAD 02", "position": "top right shoulder"},
  {"name": "PAD 03", "position": "top left"},
  {"name": "PAD 04", "position": "top middle"},
  {"name": "PAD 05", "position": "top right"},
  {"name": "PAD 06", "position": "bottom left"},
  {"name": "PAD 07", "position": "bottom middle"},
  {"name": "PAD 08", "position": "bottom right"},
  {"name": "EXT 1A", "position": "external pad 1 left input"},
  {"name": "EXT 1B", "position": "external pad 1 right input"},
  {"name": "EXT 2", "position": "external pad 2"},
  {"name": "BASS", "position": "external bass drum pedal"},
  {"name": "HAT OPE", "position": "external hi-hat pedal open"},
  {"name": "HAT MID", "position": "external hi-hat pedal middle"},
  {"name": "HAT CLO", "position": "external hi-hat pedal closed"},
  {"name": "HAT CHK", "position": "external hi-hat pedal"},
  {"name": "HAT SPL", "position": "external hi-hat pedal splash"},
]

const INTERNAL_SOUNDS = [
  '22AcBd1',
  '22AcBd2',
  'BrshBd1',
  'BrshBd2',
  '22RkBd',
  'RoomBd',
  'FusnBd',
  '1970Bd',
  'VintagBd',
  '1980Bd',
  '1984Bd',
  'FXMixBd',
  '14AcSn1',
  '14AcSnR1',
  '14FkSn1',
  '14FkSnR1',
  '14FkSn2',
  '14FkSnR2',
  'BrushSn1',
  'BrusSnR1',
  'BrshSn2',
  'BrshSnR2',
  '14JzSn',
  '14JzSnR',
  '14RkSn',
  '14RkSnR',
  '1980Sn',
  '1980SnR',
  '1984Sn',
  '1984SnR',
  'ElSn',
  'ElSnS'
  'AcTm1',
  'AcTm2',
  'AcTm3',
  'AcTm4',
  'AcTm5',
  'AcTm6',
  'BrshTm1',
  'BrshTom1',
  'BrshTm3',
  'BrshTm4',
  'BrshTm5',
  'BrshTm6',
  'FkTm1',
  'FkTm2',
  'FkTm3',
  'FkTm4',
  'FkTm5',
  'FkTm6',
  'RkTm1',
  'RkTm2',
  'RkTm3',
  'RkTm4',
  'RkTm5',
  'RkTm6',
  '1980Tm1',
  '1980Tm2',
  '1980Tm3',
  '1980Tm4',
  '1980Tm5',
  '1980Tm6',
  '1984Tm1',
  '1984Tm2',
  '1984Tm3',
  '1984Tm4',
  '1984Tm5',
  '1984Tm6',
  '1984Tm7',
  '1984Tm8',
  'ElTm1',
  'ElTm2',
  'ElTm3',
  'ElTm4',
  'ElTm5',
  'ElTm6',
  'ElTm7',
  'ElTm8',
  '21AcRd',
  'BrshRd',
  'BrshRd2',
  '20RkRd',
  'ElRd',
  'AcCr1',
  'AcCr2',
  'BrshCr1',
  'BrshCr2',
  'RkCr1',
  'RkCr2',
  'Splash',
  '14AcHHC1',
  '14AcHHOp',
  '14AcHHPd',
  'BrshHHC1',
  'BrshHHOp',
  'BrshHHPd',
  'BrshHHSp',
  '14RkHHC1',
  '14RkHHOp',
  '14RkHHPd',
  '14RkHHSp',
  '1980HHC1',
  '1980HHOp',
  '1980HHPd',
  '1980HHSp',
  '1984HHC1',
  '1984HHOp',
  '1984HHPd',
  '1984HHSp',
  'DanceHHCl',
  'DanceHHop',
  'DancHHPd',
  'DancHHSp',
  'Maracas',
  'MetroB1',
  'MtConga1',
  'MtConga2',
  'OpConga1',
  'OpConga2',
  'LowConga',
  'HiTimb1',
  'HiTimb2',
  'HiTimb3',
  'LowTimb1',
  'LowTimb2',
  'LowTimb3',
  'LowTimb4',
  'HiAgogo',
  'LowAgogo',
  'Claves',
  'JingleBl',
  'Tambrn',
  'Indian1',
  'Indian2',
  'Indian3',
  'Indian4',
  'Indian5',
  'Indian6',
  'Indian7',
  'Indian8',
  'Indian9',
  'Indian10',
  'Indian11',
  'Indian12',
  'African',
  'MarmbC3',
  'MarmbA3',
  'MarmbC4',
  'MarmbDb4',
  'MarmbD4',
  'MarmbEb4',
  'MarmbE4',
  'MarmbF4',
  'MarmbGb4',
  'MarmbG4',
  'MarmbAb4',
  'MarmbA4',
  'MarmbBb4',
  'MarmbB5',
  'MarmbC5',
  'MarmbDb5',
  'MarmbD5',
  'MarmbEb5',
  'MarmbE5',
  'MarmbF5',
  'MarmbGb5',
  'MarmbG5',
  'MarmbAb5',
  'MarmbA5',
  'MarmbBb5',
  'MarmbB5',
  'MarmbC6',
  'FX1',
  'FX2',
  'FX3',
  'FX4',
  'FX5',
  'FX6',
  'FX7',
  'FX8',
  'FX9',
  'FX10',
  'FX11',
  'One',
  'Two',
  'Three',
  'Four',
  'Five',
  'Six',
  'Seven',
  'Eight',
  'Nine',
  'Ti',
  'Ta',
  'Ei',
  'An',
  'E',
  'CBell 1',
  'CBell 2',
  'Mute',
];
